// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deliverycenter/logging/integration/v1/dc_metrics.proto

package dc_metrics

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The parameters to WriteMetricsRequest.
type WriteMetricsRequest struct {
	// Required. Message unique key.
	// source_type + source_name + ext_obj_id + int_store_id
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Required. Environment of log
	Environment string `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	// Optional. Log level. INFO Default.
	// DEBUG, INFO, WARN, ERROR.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Required. Direction of the message
	// INCOMING, OUTGOING
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Required. Object injector
	// PROVIDER, SALES_CHANNEL, ...
	SourceType string `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Required. Name of source.
	// IFOOD, RAPPI, B2W, MELI, ...
	SourceName string `protobuf:"bytes,6,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Required. Application caller
	Caller string `protobuf:"bytes,7,opt,name=caller,proto3" json:"caller,omitempty"`
	// Required. Action being executed.
	// GET_?, CREATE_?, PARSE_?, REPORT_?, RECEIVE_?, CREATE_?
	// Use simple present verbs as prefix
	Action string `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	// Required. Moment of log creation
	// Based on ISO 8601. Sample: 2020-09-11T19:02:32Z
	CreateTimestamp *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
	// Optional. Duration of the action execution
	DurationMs int32 `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Required. Type of root resource.
	// PRODUCT, ORDER
	RootResourceType string `protobuf:"bytes,11,opt,name=root_resource_type,json=rootResourceType,proto3" json:"root_resource_type,omitempty"`
	// Required. The ID related to the resource on source.
	ExtRootResourceId string `protobuf:"bytes,12,opt,name=ext_root_resource_id,json=extRootResourceId,proto3" json:"ext_root_resource_id,omitempty"`
	// Optional. The ID related to the resource on DC.
	IntRootResourceId string `protobuf:"bytes,13,opt,name=int_root_resource_id,json=intRootResourceId,proto3" json:"int_root_resource_id,omitempty"`
	// Optional. Type of child resource.
	// LISTING, ORDER_ITEM, PAYMENT, DELIVERY
	ChildResourceType string `protobuf:"bytes,14,opt,name=child_resource_type,json=childResourceType,proto3" json:"child_resource_type,omitempty"`
	// Optional. Internal id of child resource.
	ChildResourceId string `protobuf:"bytes,15,opt,name=child_resource_id,json=childResourceId,proto3" json:"child_resource_id,omitempty"`
	// Optional. The ID related to the Store on source.
	ExtStoreId string `protobuf:"bytes,16,opt,name=ext_store_id,json=extStoreId,proto3" json:"ext_store_id,omitempty"`
	// Required. The ID related to the Store on DC.
	IntStoreId string `protobuf:"bytes,17,opt,name=int_store_id,json=intStoreId,proto3" json:"int_store_id,omitempty"`
	// Optional. The error code.
	ErrorCode            string   `protobuf:"bytes,18,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteMetricsRequest) Reset()         { *m = WriteMetricsRequest{} }
func (m *WriteMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*WriteMetricsRequest) ProtoMessage()    {}
func (*WriteMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61543ba34276c52f, []int{0}
}

func (m *WriteMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteMetricsRequest.Unmarshal(m, b)
}
func (m *WriteMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteMetricsRequest.Marshal(b, m, deterministic)
}
func (m *WriteMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteMetricsRequest.Merge(m, src)
}
func (m *WriteMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_WriteMetricsRequest.Size(m)
}
func (m *WriteMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteMetricsRequest proto.InternalMessageInfo

func (m *WriteMetricsRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *WriteMetricsRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *WriteMetricsRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *WriteMetricsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *WriteMetricsRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *WriteMetricsRequest) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *WriteMetricsRequest) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *WriteMetricsRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *WriteMetricsRequest) GetCreateTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTimestamp
	}
	return nil
}

func (m *WriteMetricsRequest) GetDurationMs() int32 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

func (m *WriteMetricsRequest) GetRootResourceType() string {
	if m != nil {
		return m.RootResourceType
	}
	return ""
}

func (m *WriteMetricsRequest) GetExtRootResourceId() string {
	if m != nil {
		return m.ExtRootResourceId
	}
	return ""
}

func (m *WriteMetricsRequest) GetIntRootResourceId() string {
	if m != nil {
		return m.IntRootResourceId
	}
	return ""
}

func (m *WriteMetricsRequest) GetChildResourceType() string {
	if m != nil {
		return m.ChildResourceType
	}
	return ""
}

func (m *WriteMetricsRequest) GetChildResourceId() string {
	if m != nil {
		return m.ChildResourceId
	}
	return ""
}

func (m *WriteMetricsRequest) GetExtStoreId() string {
	if m != nil {
		return m.ExtStoreId
	}
	return ""
}

func (m *WriteMetricsRequest) GetIntStoreId() string {
	if m != nil {
		return m.IntStoreId
	}
	return ""
}

func (m *WriteMetricsRequest) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteMetricsRequest)(nil), "logging.deliverycenter.integration.v1.WriteMetricsRequest")
}

func init() {
	proto.RegisterFile("deliverycenter/logging/integration/v1/dc_metrics.proto", fileDescriptor_61543ba34276c52f)
}

var fileDescriptor_61543ba34276c52f = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xe9, 0xa0, 0x85, 0xba, 0x5d, 0xff, 0x78, 0xd3, 0x64, 0x15, 0xd0, 0xaa, 0x49, 0x93,
	0x2a, 0x84, 0x12, 0x75, 0xbb, 0x8b, 0xc4, 0x0d, 0x63, 0x17, 0x95, 0x18, 0x17, 0xd9, 0x04, 0x12,
	0x37, 0x51, 0x66, 0x1f, 0x82, 0x51, 0x62, 0x87, 0x13, 0x37, 0x6a, 0x9f, 0x8d, 0x37, 0xe2, 0x29,
	0x50, 0xec, 0xb6, 0x4b, 0xc3, 0x2e, 0x76, 0xe9, 0xef, 0xfb, 0x7d, 0xf6, 0xb1, 0x7d, 0x0e, 0xb9,
	0x14, 0x90, 0xca, 0x12, 0x70, 0xcd, 0x41, 0x19, 0x40, 0x3f, 0xd5, 0x49, 0x22, 0x55, 0xe2, 0x4b,
	0x65, 0x20, 0xc1, 0xd8, 0x48, 0xad, 0xfc, 0x72, 0xee, 0x67, 0x60, 0x50, 0xf2, 0xc2, 0xcb, 0x51,
	0x1b, 0x4d, 0xcf, 0x37, 0x94, 0xb7, 0x1f, 0xf6, 0x6a, 0x21, 0xaf, 0x9c, 0x4f, 0x4e, 0x13, 0xad,
	0x93, 0x14, 0x7c, 0x1b, 0xba, 0x5f, 0xfe, 0xf0, 0x8d, 0xcc, 0xa0, 0x30, 0x71, 0x96, 0xbb, 0x7d,
	0x26, 0xaf, 0x9b, 0x00, 0x64, 0xb9, 0x59, 0x3b, 0xf3, 0xec, 0x4f, 0x9b, 0x1c, 0x7d, 0x43, 0x69,
	0xe0, 0xc6, 0x9d, 0x1d, 0xc2, 0xef, 0x25, 0x14, 0x86, 0x9e, 0x93, 0x01, 0xd7, 0x88, 0x90, 0xda,
	0x73, 0x22, 0x29, 0x58, 0x6b, 0xda, 0x9a, 0x75, 0xc3, 0xc3, 0x9a, 0xba, 0x10, 0x74, 0x4a, 0x7a,
	0xa0, 0x4a, 0x89, 0x5a, 0x65, 0xa0, 0x0c, 0x3b, 0xb0, 0x4c, 0x5d, 0xa2, 0xc7, 0xa4, 0x9d, 0x42,
	0x09, 0x29, 0x7b, 0x6e, 0x3d, 0xb7, 0xa0, 0x6f, 0x48, 0x57, 0x48, 0x04, 0x5e, 0x6d, 0xc3, 0x5e,
	0x58, 0xe7, 0x41, 0xa0, 0xa7, 0xa4, 0x57, 0xe8, 0x25, 0x72, 0x88, 0xcc, 0x3a, 0x07, 0xd6, 0xb6,
	0x3e, 0x71, 0xd2, 0xdd, 0x3a, 0x87, 0x1a, 0xa0, 0xe2, 0x0c, 0x58, 0xa7, 0x0e, 0x7c, 0x89, 0x33,
	0xa0, 0x27, 0xa4, 0xc3, 0xe3, 0x34, 0x05, 0x64, 0x2f, 0xad, 0xb7, 0x59, 0x55, 0x7a, 0xec, 0x0e,
	0x7d, 0xe5, 0x74, 0xb7, 0xa2, 0xd7, 0x64, 0xc4, 0x11, 0x62, 0x03, 0xd1, 0xee, 0xf5, 0x58, 0x77,
	0xda, 0x9a, 0xf5, 0x2e, 0x26, 0x9e, 0x7b, 0x3e, 0x6f, 0xfb, 0x7c, 0xde, 0xdd, 0x96, 0x08, 0x87,
	0x2e, 0xb3, 0x13, 0xaa, 0xba, 0xc4, 0xd2, 0x7d, 0x4d, 0x94, 0x15, 0x8c, 0x4c, 0x5b, 0xb3, 0x76,
	0x48, 0xb6, 0xd2, 0x4d, 0x41, 0xdf, 0x13, 0x8a, 0x5a, 0x9b, 0x08, 0xa1, 0x7e, 0xc1, 0x9e, 0xad,
	0x65, 0x54, 0x39, 0x21, 0xd4, 0xae, 0xe9, 0x93, 0x63, 0x58, 0x99, 0x68, 0x3f, 0x21, 0x05, 0xeb,
	0x5b, 0x7e, 0x0c, 0x2b, 0x13, 0xd6, 0x22, 0x0b, 0x51, 0x05, 0xa4, 0x7a, 0x24, 0x70, 0xe8, 0x02,
	0x52, 0x35, 0x03, 0x1e, 0x39, 0xe2, 0x3f, 0x65, 0x2a, 0x1a, 0x05, 0x0d, 0x1c, 0x6f, 0xad, 0xbd,
	0x8a, 0xde, 0x91, 0x71, 0x83, 0x97, 0x82, 0x0d, 0x2d, 0x3d, 0xdc, 0xa3, 0x6d, 0x6f, 0xf4, 0xab,
	0xea, 0x0b, 0xa3, 0xd1, 0x62, 0x23, 0xf7, 0x4b, 0xb0, 0x32, 0xb7, 0x95, 0xe4, 0x88, 0xaa, 0xdc,
	0x1d, 0x31, 0x76, 0x84, 0x54, 0x3b, 0xe2, 0x2d, 0x21, 0x80, 0xa8, 0x31, 0xe2, 0x5a, 0x00, 0xa3,
	0xae, 0x51, 0xac, 0x72, 0xa5, 0x05, 0x5c, 0x94, 0x64, 0xb0, 0xe9, 0xdb, 0x5b, 0xc0, 0x52, 0x72,
	0xa0, 0x82, 0xf4, 0xeb, 0xed, 0x4c, 0x03, 0xef, 0x49, 0x53, 0xe4, 0x3d, 0x32, 0x03, 0x93, 0x93,
	0xff, 0xbe, 0xfe, 0xba, 0x9a, 0x9c, 0xb3, 0x67, 0x1f, 0x7f, 0x7d, 0xff, 0xd0, 0xd8, 0x8e, 0xeb,
	0xcc, 0x4f, 0x30, 0xe7, 0xfe, 0x93, 0x26, 0xfd, 0xef, 0xc1, 0xec, 0xd3, 0x86, 0xbb, 0xb2, 0x5c,
	0x10, 0x7c, 0x76, 0x60, 0x10, 0x2c, 0x1e, 0xc8, 0x20, 0xf8, 0x3a, 0xbf, 0xef, 0xd8, 0xd3, 0x2f,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xce, 0x13, 0x10, 0xb9, 0x44, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsServiceClient interface {
	// Write the dc_metrics information
	WriteMetrics(ctx context.Context, in *WriteMetricsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) WriteMetrics(ctx context.Context, in *WriteMetricsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/logging.deliverycenter.integration.v1.MetricsService/WriteMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
type MetricsServiceServer interface {
	// Write the dc_metrics information
	WriteMetrics(context.Context, *WriteMetricsRequest) (*empty.Empty, error)
}

// UnimplementedMetricsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsServiceServer struct {
}

func (*UnimplementedMetricsServiceServer) WriteMetrics(ctx context.Context, req *WriteMetricsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteMetrics not implemented")
}

func RegisterMetricsServiceServer(s *grpc.Server, srv MetricsServiceServer) {
	s.RegisterService(&_MetricsService_serviceDesc, srv)
}

func _MetricsService_WriteMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).WriteMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.deliverycenter.integration.v1.MetricsService/WriteMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).WriteMetrics(ctx, req.(*WriteMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetricsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logging.deliverycenter.integration.v1.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteMetrics",
			Handler:    _MetricsService_WriteMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliverycenter/logging/integration/v1/dc_metrics.proto",
}
